import React from 'react';
import { ArrowRight, ShieldCheck, Image, Film, Mic, Globe, MessageSquare, Star } from 'lucide-react';

interface LandingViewProps {
  onStartScan: () => void;
  onExploreDashboard: () => void;
}

export const LandingView: React.FC<LandingViewProps> = ({ onStartScan, onExploreDashboard }) => {
  const threatCategories = [
    {
      id: 'image',
      title: 'Deepfake Photos',
      badge: 'Photos & Faces',
      badgeColor: 'bg-blue-950/70 text-blue-300 border-blue-800',
      desc: 'Check if a photo or portrait was generated by AI or edited to deceive you.',
      icon: <Image className="text-blue-400" size={24} />,
      simpleNote: 'Detects AI faces & altered images',
    },
    {
      id: 'video',
      title: 'Deepfake Videos',
      badge: 'Videos & Clips',
      badgeColor: 'bg-indigo-950/70 text-indigo-300 border-indigo-800',
      desc: 'See if someone in a video is swapped, lip-synced, or digitally manipulated.',
      icon: <Film className="text-indigo-400" size={24} />,
      simpleNote: 'Finds face swaps & fake video clips',
    },
    {
      id: 'audio',
      title: 'Voice Clones',
      badge: 'Audio & Calls',
      badgeColor: 'bg-purple-950/70 text-purple-300 border-purple-800',
      desc: 'Spot fake voices and cloned speech used in fraudulent phone calls or voice notes.',
      icon: <Mic className="text-purple-400" size={24} />,
      simpleNote: 'Identifies cloned & synthetic voices',
    },
    {
      id: 'phishing',
      title: 'Phishing Websites',
      badge: 'Links & URLs',
      badgeColor: 'bg-emerald-950/70 text-emerald-300 border-emerald-800',
      desc: 'Paste any suspicious link to find out if it is trying to steal passwords or bank details.',
      icon: <Globe className="text-emerald-400" size={24} />,
      simpleNote: 'Blocks fake login & scam links',
    },
    {
      id: 'scam_msg',
      title: 'Scam Messages',
      badge: 'SMS & WhatsApp',
      badgeColor: 'bg-amber-950/70 text-amber-300 border-amber-800',
      desc: 'Check lottery, job offer, or bank alert messages before clicking or replying.',
      icon: <MessageSquare className="text-amber-400" size={24} />,
      simpleNote: 'Flags fraud lures & fake offers',
    },
    {
      id: 'fake_rev',
      title: 'Fake Reviews',
      badge: 'Product Reviews (Batch)',
      badgeColor: 'bg-rose-950/70 text-rose-300 border-rose-800',
      desc: 'Upload CSV or paste batch reviews to detect copy-paste bot rings and rating bursts.',
      icon: <Star className="text-rose-400" size={24} />,
      simpleNote: 'Catches bot syndicates via CSV batch',
    },
  ];

  return (
    <div className="max-w-7xl mx-auto px-6 py-10">
      {/* Friendly Top Welcome Banner */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-4 mb-8 rounded-2xl bg-[#111d38] border border-[#1e3a5f] text-[#f8fafc] shadow-3d-card">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-[#0077b6]/20 border border-[#00b4d8]/40 flex items-center justify-center">
            <ShieldCheck size={20} className="text-[#00b4d8]" />
          </div>
          <div>
            <span className="font-bold text-sm block text-[#f8fafc]">Safe &amp; Easy Cyber Scam Protection</span>
            <span className="text-xs text-[#94a3b8]">
              Easily verify whether photos, videos, audio, text messages, website links, or product reviews are authentic or scams.
            </span>
          </div>
        </div>
        <button
          onClick={onStartScan}
          className="px-4 py-2 rounded-xl bg-[#0077b6] hover:bg-[#0096c7] text-white font-bold text-xs shadow-3d-sm transition-all cursor-pointer"
        >
          Try Free Check
        </button>
      </div>

      {/* Hero Section */}
      <section className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center py-4 mb-16 border-b border-[#1e3a5f] pb-16">
        {/* Left Column */}
        <div className="lg:col-span-7 space-y-6">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#111d38] border border-[#1e3a5f] text-[#00b4d8] text-xs font-bold shadow-sm">
            <ShieldCheck size={16} className="text-[#00b4d8]" />
            <span>Digital Trust &amp; Cyber Safety for Everyone</span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-[#f8fafc] tracking-tight leading-[1.15] font-serif">
            Check If Images, Videos, Audio, Messages, or Websites Are Real or Fake.
          </h1>

          <p className="text-base text-[#94a3b8] leading-relaxed max-w-xl">
            With modern AI tools creating realistic fakes, anyone can be tricked. TrustNet helps you verify photos, videos, voices, messages, reviews, and web links in seconds with simple, clear results.
          </p>

          <div className="flex flex-wrap items-center gap-4 pt-2">
            <button
              onClick={onStartScan}
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-xl bg-[#0077b6] hover:bg-[#0096c7] text-white font-bold text-sm transition-all shadow-3d-sm hover:shadow-3d-md cursor-pointer"
            >
              <span>Check Media or Link Now</span>
              <ArrowRight size={16} />
            </button>

            <button
              onClick={onExploreDashboard}
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-xl bg-[#111d38] hover:bg-[#16254a] border border-[#1e3a5f] text-[#f8fafc] font-bold text-sm transition-all shadow-sm cursor-pointer"
            >
              <span>View Past Checks</span>
            </button>
          </div>

          {/* Simple Highlights */}
          <div className="grid grid-cols-3 gap-4 pt-4 border-t border-[#1e3a5f]">
            <div className="bg-[#111d38] border border-[#1e3a5f] rounded-xl p-4 shadow-sm">
              <div className="text-xl font-bold text-[#00b4d8]">Instant</div>
              <div className="text-[#94a3b8] text-xs mt-0.5">Results in 1-2 seconds</div>
            </div>
            <div className="bg-[#111d38] border border-[#1e3a5f] rounded-xl p-4 shadow-sm">
              <div className="text-xl font-bold text-[#10b981]">Simple</div>
              <div className="text-[#94a3b8] text-xs mt-0.5">Clear Real vs Fake verdict</div>
            </div>
            <div className="bg-[#111d38] border border-[#1e3a5f] rounded-xl p-4 shadow-sm">
              <div className="text-xl font-bold text-[#38bdf8]">Private</div>
              <div className="text-[#94a3b8] text-xs mt-0.5">Your files stay secure</div>
            </div>
          </div>
        </div>

        {/* Right Column: Live Detection Examples (Cybersecurity Slate & Clean) */}
        <div className="lg:col-span-5">
          <div className="rounded-2xl bg-[#111d38] border border-[#1e3a5f] shadow-3d-lg p-5">
            <div className="flex items-center justify-between pb-3 mb-4 border-b border-[#1e3a5f]">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-[#10b981] animate-pulse" />
                <span className="font-bold text-[#f8fafc] text-xs font-mono">
                  HOW TRUSTNET CHECKS THREATS
                </span>
              </div>
              <span className="px-2.5 py-0.5 rounded-md bg-[#0b132b] text-[#00b4d8] border border-[#1e3a5f] font-bold text-[11px]">
                Simple Results
              </span>
            </div>

            {/* Clear, colorful sample list */}
            <div className="space-y-3">
              {/* Photo sample */}
              <div className="p-3 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-blue-950/70 border border-blue-800 flex items-center justify-center text-blue-400">
                    <Image size={16} />
                  </div>
                  <div>
                    <span className="text-xs font-bold text-[#f8fafc] block">Photo / Portrait</span>
                    <span className="text-[11px] text-[#64748b] font-mono">profile_picture.jpg</span>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-red-950 text-red-300 border border-red-800">
                  AI Generated (Fake)
                </span>
              </div>

              {/* Video sample */}
              <div className="p-3 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-indigo-950/70 border border-indigo-800 flex items-center justify-center text-indigo-400">
                    <Film size={16} />
                  </div>
                  <div>
                    <span className="text-xs font-bold text-[#f8fafc] block">Video Clip</span>
                    <span className="text-[11px] text-[#64748b] font-mono">speech_recording.mp4</span>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-emerald-950 text-emerald-300 border border-emerald-800">
                  Authentic (Real)
                </span>
              </div>

              {/* Audio Voice sample */}
              <div className="p-3 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-purple-950/70 border border-purple-800 flex items-center justify-center text-purple-400">
                    <Mic size={16} />
                  </div>
                  <div>
                    <span className="text-xs font-bold text-[#f8fafc] block">Voice Note</span>
                    <span className="text-[11px] text-[#64748b] font-mono">urgent_call.wav</span>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-red-950 text-red-300 border border-red-800">
                  Cloned Voice (Fake)
                </span>
              </div>

              {/* Phishing link sample */}
              <div className="p-3 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-emerald-950/70 border border-emerald-800 flex items-center justify-center text-emerald-400">
                    <Globe size={16} />
                  </div>
                  <div>
                    <span className="text-xs font-bold text-[#f8fafc] block">Website Link</span>
                    <span className="text-[11px] text-[#64748b] font-mono">secure-bank-login.com</span>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-red-950 text-red-300 border border-red-800">
                  Phishing Scam
                </span>
              </div>

              {/* Scam message sample */}
              <div className="p-3 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-amber-950/70 border border-amber-800 flex items-center justify-center text-amber-400">
                    <MessageSquare size={16} />
                  </div>
                  <div>
                    <span className="text-xs font-bold text-[#f8fafc] block">SMS / Message</span>
                    <span className="text-[11px] text-[#64748b]">"You won $10,000 lottery..."</span>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-amber-950 text-amber-300 border border-amber-800">
                  Scam Detected
                </span>
              </div>

              {/* Fake review sample */}
              <div className="p-3 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-rose-950/70 border border-rose-800 flex items-center justify-center text-rose-400">
                    <Star size={16} />
                  </div>
                  <div>
                    <span className="text-xs font-bold text-[#f8fafc] block">Product Review Batch</span>
                    <span className="text-[11px] text-[#64748b]">"reviews_batch.csv"</span>
                  </div>
                </div>
                <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-rose-950 text-rose-300 border border-rose-800">
                  Bot Syndicate
                </span>
              </div>
            </div>

            <div className="mt-4 p-3 rounded-xl bg-[#080e20] border border-[#1e3a5f] text-xs flex items-center justify-between text-[#00b4d8] font-semibold">
              <span>Ready to check your own file or link?</span>
              <button
                onClick={onStartScan}
                className="text-[#00b4d8] hover:text-[#38bdf8] font-bold cursor-pointer"
              >
                Scan Now &rarr;
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* 6 Clear Threat Categories Cards */}
      <section className="mb-16">
        <div className="mb-8">
          <span className="text-xs font-bold text-[#00b4d8] uppercase tracking-wider block mb-1">
            WHAT YOU CAN CHECK
          </span>
          <h2 className="text-3xl font-bold text-[#f8fafc] font-serif">
            Detect Digital Deception Across 6 Categories
          </h2>
          <p className="text-sm text-[#94a3b8] max-w-2xl mt-1">
            Whether you received an urgent text, a suspicious voice note, a photo that looks strange, or need to audit product reviews, TrustNet gives you an immediate answer.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {threatCategories.map((item) => (
            <div
              key={item.id}
              onClick={onStartScan}
              className="bg-[#111d38] border border-[#1e3a5f] hover:border-[#00b4d8]/60 rounded-2xl p-6 shadow-3d-card hover:shadow-3d-md transition-all cursor-pointer group"
            >
              <div className="flex items-center justify-between mb-4">
                <div className="w-12 h-12 rounded-xl bg-[#0b132b] border border-[#1e3a5f] flex items-center justify-center group-hover:scale-105 transition-transform">
                  {item.icon}
                </div>
                <span className={`px-2.5 py-1 rounded-full text-[11px] font-bold border ${item.badgeColor}`}>
                  {item.badge}
                </span>
              </div>

              <h3 className="text-xl font-bold text-[#f8fafc] font-serif mb-2">
                {item.title}
              </h3>
              <p className="text-xs text-[#94a3b8] leading-relaxed mb-4">
                {item.desc}
              </p>

              <div className="flex items-center justify-between pt-3 border-t border-[#1e3a5f] text-xs font-bold text-[#00b4d8]">
                <span>{item.simpleNote}</span>
                <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform text-[#00b4d8]" />
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};
